### ISSUE TITLE
Hard coded action

### ISSUE THREAD

**Issue by carcam** [CatPointer/joomla-algolia#2]
https://github.com/CatPointer/joomla-algolia/blob/f9e55285aa781b2d9d4ea29c2e80339e66b8ebce/extensions/modules/site/mod_algolia_autocomplete/tmpl/default.php#L98

The form action is hard coded and probably it should refer to a view in the Algolia Component. From my tests the only available view should end up in a faceted search view (which will be great) but this view does not provide any results out of the box (not sure if I need to work on that in the Algolia part or in the component views).

I think the easiest way to handle this is adding a "menu item" parameter for the search results in the module configuration and calling JRoute with it:

``echo JRoute('index.php?Itemid=' . $params->('results_page'));
``

**Comment by phproberto** [comment]
Yes. This module is actually untested as it came from my Algolia integration for Structuralia which replaced a searc page that had that hardcoded search url:

https://www.structuralia.com/formacion

Indeed it will need a target page parameter when it's tested.
